# -*- coding: utf-8 -*-
"""label-indobert-kfold-7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Bl1YgCkzb0Y_QrbefDtsDqeT0FuPtId

### Directory
"""

from google.colab import drive
drive.mount('/content/drive')

pip install emoji

"""### Import Library"""

!pip install emoji
!pip install Sastrawi
!pip install transformers
!pip install scikit-learn
!pip install seaborn
!pip install torch

import pandas as pd
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from collections import defaultdict
from sklearn.model_selection import StratifiedKFold

# DataFrame

# NLP
import nltk
nltk.download('punkt')

# from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.probability import FreqDist
from nltk.tokenize import word_tokenize
import emoji

# Viz
import matplotlib.pyplot as plt
import seaborn as sns
#import matplotlib as mpl
from wordcloud import WordCloud

#Model IndoBERT
import random
import torch
import torch.nn.functional as F
from torch import optim
from tqdm import tqdm

from transformers import BertForSequenceClassification, BertConfig, BertTokenizer
from indonlu.utils.data_utils import DocumentSentimentDataset, DocumentSentimentDataLoader
from indonlu.utils.forward_fn import forward_sequence_classification
from indonlu.utils.metrics import document_sentiment_metrics_fn

"""### Dataset"""

# Import data
df = pd.read_excel('/content/drive/MyDrive/sentimen-bert-try/train-label-new.xlsx')

df

# Assuming 'label' column contains string labels
label_mapping = {'pertanyaan': 0, 'pernyataan': 1}
df['label'] = df['label'].map(label_mapping)

df = df.drop_duplicates()
df

df

df['label'] = df['label'].fillna(-1)  # Ganti NaN dengan -1 untuk diperiksa
df = df[df['label'].isin([0.0, 1.0])]  # Hapus baris dengan nilai selain 0.0 dan 1.0

df['label'] = df['label'].astype(int)

df

df.sample(5)
print(f'shape: {df.shape}')

df = df.drop_duplicates()
df

## Proporsi Variabel Target
df['label'].value_counts()

# Function to make a donut chart
def donut(sizes, ax, angle=90, labels=None,colors=None, explode=None, shadow=None):

    # Plot
    ax.pie(sizes, colors = colors, labels=labels, autopct='%.1f%%',
           startangle = angle, pctdistance=0.8, explode = explode,
           wedgeprops=dict(width=0.4), shadow=shadow)

    # Formatting
    plt.axis('equal')
    plt.tight_layout()

# Plot arguments
sizes = df.label.value_counts()
labels = ['Pernyataan', 'Pertanyaan']
colors = ['pink', 'lavender']
explode = (0,0)

# Create axes
f, ax = plt.subplots(figsize=(6,4))

# plot donut
donut(sizes, ax, 90, labels, colors=colors, explode=explode, shadow=True)
ax.set_title('Label Sentiment Proportions')

plt.show()

import re
import numpy as np
import emoji

def repeatchar_clean(text):
    """Menghapus karakter yang berulang lebih dari dua kali."""
    return re.sub(r'(.)\1{2,}', r'\1', text)

def clean_text(text):
    """Membersihkan teks dari karakter yang tidak relevan untuk analisis BERT."""
    # Ubah enter menjadi spasi
    text = text.replace('\n', ' ')

    # Hapus emoji
    text = emoji.demojize(text)  # Convert emoji ke format teks
    text = re.sub(r':[A-Za-z_-]+:', ' ', text)  # Hapus format teks emoji

    # Hapus emoticon
    text = re.sub(r"([xX;:]'?[dDpPvVoO3)(])", ' ', text)

    # Hapus URL/link
    text = re.sub(r'https?://\S+|www\.\S+', '', text)

    # Hapus username (@mention)
    text = re.sub(r'@[A-Za-z0-9_]+', '', text)

    # Hapus hashtag (# tetap mempertahankan kata setelahnya)
    text = re.sub(r'#(\S+)', r'\1', text)

    # Hapus karakter berulang
    text = repeatchar_clean(text)

    # Hapus angka dan simbol tertentu (tapi biarkan tanda baca penting seperti ?, !, .)
    text = re.sub(r'[^a-zA-Z0-9?!., ]+', ' ', text)

    # Hapus spasi berlebih
    text = re.sub(r'\s+', ' ', text).strip()

    return text

def preprocess_bert(df):
    """Preprocessing untuk dataset sebelum masuk ke model BERT."""
    df_pp = df.copy()
    df_pp['text'] = df_pp['text'].astype(str).map(clean_text)

    # Hapus baris kosong setelah preprocessing
    df_pp['text'].replace('', np.nan, inplace=True)
    df_pp['text'].replace(' ', np.nan, inplace=True)
    df_pp.dropna(subset=['text'], inplace=True)

    return df_pp

df = preprocess_bert(df)

df

pip install datasets

pip install Dataset

# Create or update the dataset
from datasets import Dataset
dataset = Dataset.from_pandas(df)

# dataset["train"][0]

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("ayameRushia/indobert-base-uncased-finetuned-indonlu-smsa")

dataset

# Get the maximum sequence length in your dataset
max_seq_length = max(len(tokenizer(text)["input_ids"]) for text in df["text"])

# Tokenize function
def tokenize_function(examples):
    tokenized_inputs = tokenizer(examples["text"], padding="max_length", truncation=True, return_tensors="pt", max_length=max_seq_length)
    return {"input_ids": tokenized_inputs["input_ids"], "attention_mask": tokenized_inputs["attention_mask"], "label": examples["label"]}

# Tokenize the dataset
tokenized_dataset = dataset.map(tokenize_function, batched=True)

from transformers import DefaultDataCollator

data_collator = DefaultDataCollator()

# from transformers import BertForSequenceClassification, TrainingArguments, Trainer

# model = BertForSequenceClassification.from_pretrained("ayameRushia/bert-base-indonesian-1.5G-sentiment-analysis-smsa")

pip install wandb

import wandb

wandb.login()

pip install accelerate -U

from transformers import Trainer

from transformers import TrainingArguments

df

pipeline = 'text-classification'

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from transformers import TrainingArguments, BertForSequenceClassification, Trainer, BertTokenizer
from datasets import Dataset
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
import torch

# Initialize the tokenizer
tokenizer = BertTokenizer.from_pretrained("ayameRushia/indobert-base-uncased-finetuned-indonlu-smsa")

# Number of folds for cross-validation
num_folds = 7

# Define the training arguments
training_args = TrainingArguments(k
    output_dir="label-indobert",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=10,
    weight_decay=0.01,
    save_total_limit=1,  # For saving only the best model
    save_strategy="epoch",
    logging_dir="./logs",
    logging_strategy="epoch"
)

# Tokenization function
def tokenize_function(examples):
    tokenized_inputs = tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128,  # Ensure max_length is consistent with your model's needs
    )
    return {
        "input_ids": tokenized_inputs["input_ids"],
        "attention_mask": tokenized_inputs["attention_mask"],
        "label": examples["label"],
    }

# Convert DataFrame to Dataset
dataset = Dataset.from_pandas(df)

# Initialize lists to store evaluation results
accuracies = []
precisions = []
recalls = []
f1_scores = []

# Stratified K-Fold Cross-Validation
skf = StratifiedKFold(n_splits=num_folds, shuffle=True, random_state=42)

for fold, (train_idx, val_idx) in enumerate(skf.split(df["text"], df["label"])):
    print(f"\nFold {fold + 1}/{num_folds}")

    # Split the data into training and validation sets
    train_data = df.iloc[train_idx]
    val_data = df.iloc[val_idx]

    # Preprocess and tokenize the data
    train_dataset = Dataset.from_pandas(train_data)
    val_dataset = Dataset.from_pandas(val_data)

    tokenized_train_dataset = train_dataset.map(tokenize_function, batched=True)
    tokenized_val_dataset = val_dataset.map(tokenize_function, batched=True)


    # Load model and tokenizer
    model_name = "ayameRushia/indobert-base-uncased-finetuned-indonlu-smsa"
    model = AutoModelForSequenceClassification.from_pretrained(model_name)
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    # Move model to GPU if available
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)

    # Create pipeline
    text_pipeline = pipeline(
        "text-classification",
        model=model,
        tokenizer=tokenizer,
        device=0 if torch.cuda.is_available() else -1
    )

    # Define Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train_dataset,
        eval_dataset=tokenized_val_dataset,
        tokenizer=tokenizer,
    )

    # Train the model
    trainer.train()

    # Evaluate the model on the validation set
    results = trainer.predict(tokenized_val_dataset)

    # Extract predictions and labels
    predictions = results.predictions.argmax(axis=1)
    labels = tokenized_val_dataset["label"]

    # Calculate metrics for this fold
    accuracy = accuracy_score(labels, predictions)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average="weighted")

    # Append results to lists
    accuracies.append(accuracy)
    precisions.append(precision)
    recalls.append(recall)
    f1_scores.append(f1)

# Calculate and print average metrics across all folds
avg_accuracy = sum(accuracies) / num_folds
avg_precision = sum(precisions) / num_folds
avg_recall = sum(recalls) / num_folds
avg_f1 = sum(f1_scores) / num_folds

print("\n=== Cross-Validation Results ===")
print(f"Average Accuracy: {avg_accuracy:.4f}")
print(f"Average Precision: {avg_precision:.4f}")
print(f"Average Recall: {avg_recall:.4f}")
print(f"Average F1-score: {avg_f1:.4f}")

trainer.save_model('/content/drive/MyDrive/sentimen-bert-try/label-indobert-kfold-7')

import pandas as pd
from transformers import pipeline
import re
import numpy as np
import emoji

# Load model
sentiment_model = pipeline("sentiment-analysis", model="/content/drive/MyDrive/sentimen-bert-try/label-indobert-kfold-7")

# Preprocessing functions (dari kode Anda)
def repeatchar_clean(text):
    """Menghapus karakter yang berulang lebih dari dua kali."""
    return re.sub(r'(.)\1{2,}', r'\1', text)

def clean_text(text):
    """Membersihkan teks dari karakter yang tidak relevan untuk analisis BERT."""
    text = text.replace('\n', ' ')  # Ubah enter menjadi spasi
    text = emoji.demojize(text)  # Convert emoji ke format teks
    text = re.sub(r':[A-Za-z_-]+:', ' ', text)  # Hapus format teks emoji
    text = re.sub(r"([xX;:]'?[dDpPvVoO3)(])", ' ', text)  # Hapus emoticon
    text = re.sub(r'https?://\S+|www\.\S+', '', text)  # Hapus URL/link
    text = re.sub(r'@[A-Za-z0-9_]+', '', text)  # Hapus username (@mention)
    text = re.sub(r'#(\S+)', r'\1', text)  # Hapus hashtag (# tetap mempertahankan kata setelahnya)
    text = repeatchar_clean(text)  # Hapus karakter berulang
    text = re.sub(r'[^a-zA-Z0-9?!., ]+', ' ', text)  # Hapus angka dan simbol tertentu
    text = re.sub(r'\s+', ' ', text).strip()  # Hapus spasi berlebih
    return text

def preprocess_bert(df):
    """Preprocessing untuk dataset sebelum masuk ke model BERT."""
    df_pp = df.copy()
    df_pp['text'] = df_pp['text'].astype(str).map(clean_text)
    df_pp['text'].replace('', np.nan, inplace=True)  # Hapus baris kosong setelah preprocessing
    df_pp['text'].replace(' ', np.nan, inplace=True)
    df_pp.dropna(subset=['text'], inplace=True)
    return df_pp

# Load dataset
input_file = "/content/drive/MyDrive/sentimen-bert-try/testing.xlsx"  # Replace with the correct path to your file
data = pd.read_excel(input_file)

# Pastikan ada kolom 'text'
if "text" not in data.columns:
    raise ValueError("Kolom 'text' tidak ditemukan dalam file.")

# Preprocess dataset
data_preprocessed = preprocess_bert(data)

# Inisialisasi list untuk hasil
original_texts = data["text"].tolist()
processed_texts = data_preprocessed["text"].tolist()
predicted_labels = []

# Lakukan prediksi
for text in processed_texts:
    prediction = sentiment_model(text)
    predicted_labels.append(prediction[0]["label"])  # Simpan label prediksi

# Tambahkan hasil ke DataFrame
data_preprocessed["Text"] = original_texts
data_preprocessed["Predicted Label"] = predicted_labels

# Simpan hasil ke file CSV
output_file = "/content/drive/MyDrive/sentimen-bert-try/testing-result-label-kfold7.csv"  # Ganti dengan path untuk menyimpan hasil
data_preprocessed[["Text", "text", "Predicted Label"]].rename(columns={"text": "Processed Text"}).to_csv(output_file, index=False)

print(f"Hasil prediksi berhasil disimpan ke {output_file}")

import pandas as pd
input_file = "/content/drive/MyDrive/sentimen-bert-try/testing-result-label-kfold7.xlsx"
data = pd.read_excel(input_file)
data

#try main project

comment_text = "mati yg ga wajar.. air keluar ga keluar ga,, skrg malah ga keluar .. kmren siang sampek jam 11 malam mati, keluar trs shubuh mati lagi sampek skrg????? .. kali ini bnr2 parah"

from transformers import pipeline

comment = pipeline("text-classification", model='/content/drive/MyDrive/sentimen-bert-try/label-indobert-kfold-7')
comment(comment_text)

comment_text = "terima kasih pdam sudah dikirim air tangki"

from transformers import pipeline

comment = pipeline("text-classification", model='/content/drive/MyDrive/sentimen-bert-try/label-indobert')
comment(comment_text)

comment_text = "kapan ya diperbaiki?"

from transformers import pipeline

comment = pipeline("sentiment-analysis", model="/content/drive/MyDrive/sentimen-bert-try/label-indobert")
comment(comment_text)

comment_text = "Kulihat2 komen paling komplain air mati doang , jarang banget komplain air bau / keruh , apa cuma daerahku doang ya 🤢 Bener2 parah banget bau sama keruhnya , boro2 dipakai masak , dipakai mandi aja mikir2"

from transformers import pipeline

comment = pipeline("sentiment-analysis", model="/content/drive/MyDrive/sentimen-bert-try/label-indobert")
comment(comment_text)

comment_text = "pemakaian saya sejak bulan sept kurang lebih sama, tapi kenapa nilai tagihannya hingga januari 2023 ini naik terus"

from transformers import pipeline

comment = pipeline("sentiment-analysis", model="/content/drive/MyDrive/sentimen-bert-try/label-indobert")
comment(comment_text)

comment_text = "terimakasih pdam airnya sudah kembali normal"

from transformers import pipeline

comment = pipeline("sentiment-analysis", model="/content/drive/MyDrive/sentimen-bert-try/label-indobert")
comment(comment_text)

comment_text = "Meter sya mati (ngak jalan) sdh lapor cuma dilihat saja tindak lanjutnya belum tampakJl. Kalisari Gg 3/1 surabaya"

from transformers import pipeline

comment = pipeline("sentiment-analysis", model="/content/drive/MyDrive/sentimen-bert-try/label-indobert")
comment(comment_text)

comment_text = "Air di rumah keruh/kotor sudah 3 hari ini ngadu tp tdk ada penanganan sama sekali kenapa lambat banget ya?😃"

from transformers import pipeline

comment = pipeline("sentiment-analysis", model="/content/drive/MyDrive/sentimen-bert-try/label-indobert")
comment(comment_text)

comment_text = "habis lapor air keluar pelan cenderung MATI, tapi setelah di survey dan penjelasan. 2-3 hari air JOSS seperti pake pompa air 👏👏👏 terimakasih atas pelayanan nya"

from transformers import pipeline

comment = pipeline("sentiment-analysis", model="/content/drive/MyDrive/sentimen-bert-try/label-indobert")
comment(comment_text)

####################################################

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Calculate confusion matrix
cm = confusion_matrix(labels, predictions)

# Create a DataFrame for better visualization
class_names = ['pertanyaan', 'pernyataan']
df_cm = pd.DataFrame(cm, index=class_names, columns=class_names)

# Function to display confusion matrix
def show_confusion_matrix(confusion_matrix):
    hmap = sns.heatmap(confusion_matrix, annot=True, fmt="d", cmap="Blues")
    hmap.yaxis.set_ticklabels(hmap.yaxis.get_ticklabels(), rotation=0, ha='right')
    hmap.xaxis.set_ticklabels(hmap.xaxis.get_ticklabels(), rotation=30, ha='right')
    plt.ylabel('True sentiment')
    plt.xlabel('Predicted sentiment')

# Display confusion matrix
show_confusion_matrix(df_cm)
plt.show()

